# 連絡手段
contact_means:
  - {
      type:  'form',
      title: '新歓イベント参加申し込みはこちら',
      label: '@kyodai_kongoh',
      url:   'https://forms.gle/91XDBYjmZqbsRFjcA',
      icon:  ''
    }
  - {
      type:  'form',
      title: '見学・入会に関するお問合せはこちら',
      label: '@kyodai_kongoh',
      url:   'https://forms.gle/pEQhKVD3DswEu3NG8',
      icon:  ''
    }
  - {
      type:    'mail',
      title:   'その他のご連絡はこちらから',
      address: 'kyodai.g@gmail.com',
      icon:    ''
    }
  - {
      type:  'sns',
      title: 'Twitter',
      label: '@kyodai_kongoh',
      url:   'https://twitter.com/kyodai_kongoh',
      icon:  ''
    }
  - {
      type:  'sns',
      title: 'Instagram',
      label: 'kyodai_kongoh',
      url:   'https://www.instagram.com/kyodai_kongoh/',
      icon:  ''
    }
# view内で利用する文言
views:
  top:
    headline:
      title: '金剛会は年中入部大歓迎！'
      topics:
        - "geocities閉鎖に伴いサイト移転いたしました。('18.10.17)"
        - 'ここは新しいサイトです。ブックマーク等の対処をお願いいたします。'
    contact:
      topics:
        - '私たちは入会を年中歓迎しております。'
        - 'お気軽にTwitter、メールなどで連絡を！'
        - 'お稽古の見学なども承っております。'
        - '令和３年も絶賛新歓中！'
        - '心から新入部員を募集しております！！'
        - '何回生でも、何大生でも大歓迎です！！！'
